### ISSUE TITLE
Full plan, but downloading model is limited

### ISSUE THREAD

**Issue by yiboz2001** [BlenderKit/platform#17]
### Bug Description

I am a **blenderkit Full Plan subscriber**, but downloading 3d models seems to be limited.
For example, when I try to download the resulotion_4K file of model (https://www.blenderkit.com/get-blenderkit/c0ae0e81-89a5-47c6-8bd8-97e3dfbec8d1/), the local client responses that: 
```
{
    "detail": "Users plan doesnt allow to download this: Limit of models exceeded. The limit is 10000 items.",
    "statusCode": 403
}
```
, but I don't find any instructions on limiting the number of downloads on the subscription page.

Any help will be highly appreciated.

### Error Logs

```
{
    "detail": "Users plan doesnt allow to download this: Limit of models exceeded. The limit is 10000 items.",
    "statusCode": 403
}
```

**Comment by agajdosi** [comment]
Hi @yiboz2001, thank you for the update. This needs to be solved. I have notified the team, we will update here once there is progress on this.

**Comment by agajdosi** [comment]
@yiboz2001 The limit comes from a technical solution protecting the service against DDOS and other types of the attack and overusage caused by scripting and other non-manual usage of the server. The limit applies to each asset type separately, which makes over 50k downloads available per month. We believe this is a way above the powers to click and needs of anybody.

If your use case is to download the whole database for academic research, business activities or other needs which uses scripting, please contact our support at: admin@blenderkit.com. If you are unhappy with the limit and it does not match your expectations, please write to admin@blenderkit.com for a refund. Have a nice day!

**Comment by luigicaval** [comment]
I have the same issue, I cannot download **models.** I have the full plan for one month, it ends may the 10th (now april the 29th).

It seems I can only download materials, scenes, but now it is claimed that I reached the limit of downloads when I try to download models? But I am very far from these 50 k limits! Moreover it is claimed on the website that **The number of product downloads per your subscription period is unlimited.**

Help.... ?
