### ISSUE TITLE
Download API

### ISSUE THREAD

**Issue by rafay-pk** [BlenderKit/platform#18]
### Is your feature request related to a problem or weakness of addon? Please describe.

I recently got to know about blenderkit and was browsing the library. The assets seemed good so I bought an annual subscription.
The problem I'm facing is that lets say I want 100 models of boxes. Do you guys really expect me to search and drag a 100 times to get the 3d models I need?

I downloaded the plugin and started digging around in the python files to find the download API but everything seems convoluted as someone coming from the outside.

Am I missing some documentation? If so, please link me to it.

### Describe the solution you'd like

A simple download function that takes in a list of model_ids would be much appreciated.

**Comment by agajdosi** [comment]
Hello @rafay-pk, yes we actually expect the user to search, choose and drag the asset into the scene, then tune the scene, make the details, all the hard work to make a good 3D render. In comparison to searching and choosing, which would still be needed to get the list of IDs, and the 3D work, the drag and drop is just a small task which does not consume much time (in comparison to the steps mentioned before). We are not stopping you from studying the code, creating the script, or even creating PR to the add-on repository if you really need this usecase. But we cannot provide support or allocate developer resources to this, because we allocate them to improve the experience of the artist users, because we expect human users who work in Blender to use BlenderKit, not automated scripts to download as much as possible. This is also clearly stated in our terms and conditions: `8. user (or "you") is a person using the interface and/or purchasing subscription via the interface;`.
