### ISSUE TITLE
"Waiting for redistribution" is not showing

### ISSUE THREAD

**Issue by karolinahuserkova** [BlenderKit/platform#4]
### Bug Description

Toto nám dnes užívatel nahlásil do emailu @PetrDlouhy 

Hello, 
I would like to report all of a sudden all my assets lost all waiting for redistribution. Until yesterday, practically everyone had from a few to more than 20 and today suddenly all of them have 0, at the same time the amount already redistributed has not changed. A sample screenshot is attached. My username is Dal Roron.
![Screenshot_20240208_091440_Vivaldi](https://github.com/BlenderKit/blenderkit/assets/104030026/b2cf6f52-029d-48f9-82be-5def530a0dcb)
![Screenshot_20240208_091147_Vivaldi](https://github.com/BlenderKit/blenderkit/assets/104030026/7afbe7d1-b816-4637-9228-45af4ad80794)

Regards

- bude to asi nejaký bug jak ste riešili tie prepočty atď.

### Steps to Reproduce

1. 
2. 
3.

**Comment by karolinahuserkova** [comment]
teď to nahlásil ješte aj tento užívateľ: vendol21@gmail.com, podobný problém:

Hello, im Vasilis the chroma3d creator, this morning all my waiting for redistribution dowloads are zero, there is a problem with the site?

Have a nice day. 
Vasilis.

**Comment by PetrDlouhy** [comment]
We were adjusting the proces for recalculating these numbers.
Probably there is bug in the new proces, but the bug can't affect the base data. Only the numbers shown on My Assets page are not correct.

The recalculation process is already running and will finish probably in ~2 hours which should bring back the correct values. 

I will resolve this issue today, so that even during the recalculation the numbers will not be affected.

**Comment by PetrDlouhy** [comment]
The most probable cause of this is that the recalculation process crashed at very unfortunate moment between setting all values to 0 and updating them with correct values.

**Comment by PetrDlouhy** [comment]
Now the values are back. I hope this is fixed, so I am closing the issue.
